import type { KarutaCard } from '../interfaces/karuta-card.interface';

const KARUTA_CARD_ASSET_PATH = './public/assets/images/karuta-cards';

export const KARUTA_CARDS: KarutaCard[] = [
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/01_akino.jpg`,
		identifyingCharacters: 'akino',
		verseFirstPart: 'aki no ta no \n kariho no io no \n toma wo arami',
		verseSecondPart: 'wa ga koromode wa \n tsuyu ni nuretsutsu',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/02_harusu.jpg`,
		identifyingCharacters: 'harusu',
		verseFirstPart: 'haru sugite \n natsu kinikerashi \n shirotae no',
		verseSecondPart: 'koromo hosu chō \n Ama no Kaguyama',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/03_ashi.jpg`,
		identifyingCharacters: 'ashi',
		verseFirstPart: 'ashibiki no \n yamadori no ō no \n shidari no ō no',
		verseSecondPart: 'naga nagashi yo wo \n	hitori kamo nen',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/04_tago.jpg`,
		identifyingCharacters: 'tago',
		verseFirstPart: 'tago no ura ni \n uchi idete mireba \n shirotae no',
		verseSecondPart: 'fuji no takane ni \n yuki wa furitsutsu',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/05_oku.jpg`,
		identifyingCharacters: 'oku',
		verseFirstPart: 'okuyama ni \n momiji fumiwake \n naku shika no',
		verseSecondPart: 'koe kiku toki zo \n aki wa kanashiki',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/06_kasa.jpg`,
		identifyingCharacters: 'kasa',
		verseFirstPart: 'kasasagi no \n wataseru hashi ni \n oku shimo no',
		verseSecondPart: 'shiroki wo mireba \n yo zo fukenikeru',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/07_amano.jpg`,
		identifyingCharacters: 'amano',
		verseFirstPart: 'ama no hara \n furisake mireba \n kasuga naru',
		verseSecondPart: 'Mikasa no yama ni \n ideshi tsuki kamo',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/08_wagai.jpg`,
		identifyingCharacters: 'wagai',
		verseFirstPart: 'wa ga io wa \n miyako no tatsumi \n shika zo sumu',
		verseSecondPart: 'yo wo ujiyama to \n hito wa iu nari',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/09_hanano.jpg`,
		identifyingCharacters: 'hanano',
		verseFirstPart: 'hana no iro wa \n utsurinikeri na \n itazura ni',
		verseSecondPart: 'wa ga mi yo ni furu \n nagame seshi ma ni',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/10_kore.jpg`,
		identifyingCharacters: 'kore',
		verseFirstPart: 'kore ya kono \n yuku mo kaeru mo \n wakarete wa',
		verseSecondPart: 'shiru mo shiranu mo \n Ōsaka no seki',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/11_watanoharaya.jpg`,
		identifyingCharacters: 'watanoharaya',
		verseFirstPart: 'wata no hara \n yasoshima kakete \n kogi idenu to',
		verseSecondPart: 'hito ni wa tsugeyo \n ama no tsuribuné',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/12_amatsu.jpg`,
		identifyingCharacters: 'amatsu',
		verseFirstPart: 'ama tsu kaze \n kumo no kayoiji \n fuki toji yo',
		verseSecondPart: 'otome no sugata \n shibashi todomen',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/13_tsuku.jpg`,
		identifyingCharacters: 'tsuku',
		verseFirstPart: 'Tsukuba-ne no \n mine yori otsuru \n minano-gawa',
		verseSecondPart: 'koi zo tsumorite \n fuchi to narinuru',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/14_michi.jpg`,
		identifyingCharacters: 'michi',
		verseFirstPart: 'michinoku no \n Shinobu mojizuri \n tare yue ni',
		verseSecondPart: 'midare some ni \n ware naranaku ni',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/15_kimigatameha.jpg`,
		identifyingCharacters: 'kimigatameha',
		verseFirstPart: 'kimi ga tame \n haru no no ni idete \n wakana tsumu',
		verseSecondPart: 'waga koromode ni \n yuki wa furitsutsu',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/16_tachi.jpg`,
		identifyingCharacters: 'tachi',
		verseFirstPart: 'tachiwakare \n inaba no yama no \n mine ni ouru',
		verseSecondPart: 'matsu to shi kikaba \n ima kaeri-kon',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/17_chiha.jpg`,
		identifyingCharacters: 'chiha',
		verseFirstPart: 'chihayaburu \n kami-yo mo kikazu \n tatsuta-gawa',
		verseSecondPart: 'kara-kurenai ni \n mizu kuguru to wa',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/18_su.jpg`,
		identifyingCharacters: 'su',
		verseFirstPart: 'sumi no e no \n kishi ni yoru nami \n yoru sae ya',
		verseSecondPart: 'yume no kayoi ji \n hito me yoku ran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/19_naniwaga.jpg`,
		identifyingCharacters: 'naniwaga',
		verseFirstPart: 'Naniwa gata \n mijikaki ashi no \n fushi no ma mo',
		verseSecondPart: 'awade kono yo wo \n sugushite yo to ya',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/20_wabi.jpg`,
		identifyingCharacters: 'wabi',
		verseFirstPart: 'wabi nureba \n ima hata onaji \n naniwa naru',
		verseSecondPart: 'mi wo tsukushitemo \n awan to zo omou',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/21_imako.jpg`,
		identifyingCharacters: 'imako',
		verseFirstPart: 'ima kon to \n iishi bakari ni \n nagatsuki no',
		verseSecondPart: 'ariake no tsuki wo \n machi idetsuru ka na',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/22_fu.jpg`,
		identifyingCharacters: 'fu',
		verseFirstPart: 'fuku kara ni \n aki no kusaki no \n shiorureba',
		verseSecondPart: 'mube yamakaze wo \n arashi to iuran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/23_tsuki.jpg`,
		identifyingCharacters: 'tsuki',
		verseFirstPart: 'tsuki mireba \n chiji ni mono koso \n kanashi kere',
		verseSecondPart: 'waga mi hitotsu no \n aki ni wa aranedo',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/24_kono.jpg`,
		identifyingCharacters: 'kono',
		verseFirstPart: 'kono tabi wa nusa mo \n toriaezu tamuke yama',
		verseSecondPart: 'momiji no nishiki \n kami no mani mani',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/25_nanishi.jpg`,
		identifyingCharacters: 'nanishi',
		verseFirstPart: 'na ni shi owaba \n osakayama no \n sanekazura',
		verseSecondPart: 'hito ni shirarede \n kuru yoshi mo gana',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/26_ogu.jpg`,
		identifyingCharacters: 'ogu',
		verseFirstPart: 'ogurayama \n mine no mojijiba \n kokoro araba',
		verseSecondPart: 'ima hitotabi no \n miyuki matanan',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/27_mikano.jpg`,
		identifyingCharacters: 'mikano',
		verseFirstPart: 'mika no hara \n wakite nagaruru \n izumi-gawa',
		verseSecondPart: 'itsu mi kitote ka \n koishi karuran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/28_yamaza.jpg`,
		identifyingCharacters: 'yamaza',
		verseFirstPart: 'yamazato wa \n fuyu zo sabishisa \n masarikeru',
		verseSecondPart: 'hitome mo kusa mo \n karenu omoeba',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/29_kokoroa.jpg`,
		identifyingCharacters: 'kokoroa',
		verseFirstPart: 'kokoroate ni \n orabaya oran \n hatsushimo no',
		verseSecondPart: 'oki madowaseru \n shiragiku no hana',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/30_aria.jpg`,
		identifyingCharacters: 'aria',
		verseFirstPart: 'ariake no \n tsurenaku mieshi \n wakare yori',
		verseSecondPart: 'akatsuki bakari \n uki mono wa nashi',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/31_asaborakea.jpg`,
		identifyingCharacters: 'asaborakea',
		verseFirstPart: 'asaborake \n ariake no tsuki to \n miru made ni',
		verseSecondPart: 'yoshino no sato ni \n fureru shirayuki',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/32_yamaga.jpg`,
		identifyingCharacters: 'yamaga',
		verseFirstPart: 'yamagawa ni \n kaze no kaketaru \n shigarami wa',
		verseSecondPart: 'nagaremo aenu \n momiji narikeri',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/33_hisa.jpg`,
		identifyingCharacters: 'hisa',
		verseFirstPart: 'hisakata no \n hikari nodokeki \n haru no hi ni',
		verseSecondPart: 'shizu-gokoro naku \n hana no chiruran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/34_tare.jpg`,
		identifyingCharacters: 'tare',
		verseFirstPart: 'tare wo kamo \n shiru hito ni sen \n takasago no',
		verseSecondPart: 'matsu mo mukashi no \n tomo nara naku ni',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/35_hitowa.jpg`,
		identifyingCharacters: 'hitowa',
		verseFirstPart: 'hito wa isa \n kokoro mo shirazu \n furusato wa',
		verseSecondPart: 'hana zo mukashi no \n ka ni nioikeru',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/36_natsu.jpg`,
		identifyingCharacters: 'natsu',
		verseFirstPart: 'natsu no yo wa \n mada yoi nagara \n akenuru wo',
		verseSecondPart: 'kumo no izuko ni \n tsuki yadoru ran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/37_shira.jpg`,
		identifyingCharacters: 'shira',
		verseFirstPart: 'shiratsuyu wo \n kaze no fukishiku \n aki no no wa',
		verseSecondPart: 'tsuranuki tomenu \n tama zo chiri keru',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/38_wasura.jpg`,
		identifyingCharacters: 'wasura',
		verseFirstPart: 'wasuraruru \n mi wo ba omowazu \n chikaite shi',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/39_asaji.jpg`,
		identifyingCharacters: 'asaji',
		verseFirstPart: 'asajiu no \n ono no shinohara \n shinoburedo',
		verseSecondPart: 'amarite nado ka \n hito no koishiki',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/40_shino.jpg`,
		identifyingCharacters: 'shino',
		verseFirstPart: 'shinoburedo \n iro ni idenikeri \n wa ga koi wa',
		verseSecondPart: 'mono ya omou to \n hito no tou made',
	},
	// https://onethousandsummers.blogspot.com/p/chouyaku-hyakuninisshu.html
	// https://100poets.com/index/
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/41_koi.jpg`,
		identifyingCharacters: 'koi',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/42_chigiriki.jpg`,
		identifyingCharacters: 'chigiriki',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/43_ai.jpg`,
		identifyingCharacters: 'ai',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/44_ooko.jpg`,
		identifyingCharacters: 'ooko',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/45_aware.jpg`,
		identifyingCharacters: 'aware',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/46_yura.jpg`,
		identifyingCharacters: 'yura',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/47_yae.jpg`,
		identifyingCharacters: 'yae',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/48_kazeo.jpg`,
		identifyingCharacters: 'kazeo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/49_mikaki.jpg`,
		identifyingCharacters: 'mikaki',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/50_kimigatameo.jpg`,
		identifyingCharacters: 'kimigatameo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/51_kaku.jpg`,
		identifyingCharacters: 'kaku',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/52_ake.jpg`,
		identifyingCharacters: 'ake',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/53_nageki.jpg`,
		identifyingCharacters: 'nageki',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/54_wasure.jpg`,
		identifyingCharacters: 'wasure',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/55_taki.jpg`,
		identifyingCharacters: 'taki',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/56_araza.jpg`,
		identifyingCharacters: 'araza',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/57_me.jpg`,
		identifyingCharacters: 'me',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/58_arima.jpg`,
		identifyingCharacters: 'arima',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/59_yasu.jpg`,
		identifyingCharacters: 'yasu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/60_ooe.jpg`,
		identifyingCharacters: 'ooe',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/61_ini.jpg`,
		identifyingCharacters: 'ini',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/62_yoo.jpg`,
		identifyingCharacters: 'yoo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/63_imawa.jpg`,
		identifyingCharacters: 'imawa',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/64_asaborakeu.jpg`,
		identifyingCharacters: 'asaborakeu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/65_ura.jpg`,
		identifyingCharacters: 'ura',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/66_moro.jpg`,
		identifyingCharacters: 'moro',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/67_haruno.jpg`,
		identifyingCharacters: 'haruno',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/68_kokoroni.jpg`,
		identifyingCharacters: 'kokoroni',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/69_arashi.jpg`,
		identifyingCharacters: 'arashi',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/70_sa.jpg`,
		identifyingCharacters: 'sa',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/71_yuu.jpg`,
		identifyingCharacters: 'yuu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/72_oto.jpg`,
		identifyingCharacters: 'oto',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/73_taka.jpg`,
		identifyingCharacters: 'taka',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/74_uka.jpg`,
		identifyingCharacters: 'uka',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/75_chigirio.jpg`,
		identifyingCharacters: 'chigirio',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/76_watanoharako.jpg`,
		identifyingCharacters: 'watanoharako',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/77_se.jpg`,
		identifyingCharacters: 'se',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/78_awaji.jpg`,
		identifyingCharacters: 'awaji',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/79_akika.jpg`,
		identifyingCharacters: 'akika',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/80_nagaka.jpg`,
		identifyingCharacters: 'nagaka',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/81_ho.jpg`,
		identifyingCharacters: 'ho',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/82_omo.jpg`,
		identifyingCharacters: 'omo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/83_yononakayo.jpg`,
		identifyingCharacters: 'yononakayo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/84_nagara.jpg`,
		identifyingCharacters: 'nagara',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/85_yomo.jpg`,
		identifyingCharacters: 'yomo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/86_nageke.jpg`,
		identifyingCharacters: 'nageke',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/87_mu.jpg`,
		identifyingCharacters: 'mu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/88_naniwae.jpg`,
		identifyingCharacters: 'naniwae',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/89_tama.jpg`,
		identifyingCharacters: 'tama',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/90_mise.jpg`,
		identifyingCharacters: 'mise',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/91_kiri.jpg`,
		identifyingCharacters: 'kiri',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/92_wagaso.jpg`,
		identifyingCharacters: 'wagaso',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/93_yononakawa.jpg`,
		identifyingCharacters: 'yononakawa',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/94_miyo.jpg`,
		identifyingCharacters: 'miyo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/95_ooke.jpg`,
		identifyingCharacters: 'ooke',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/96_hanasa.jpg`,
		identifyingCharacters: 'hanasa',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/97_konu.jpg`,
		identifyingCharacters: 'konu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/98_kazeso.jpg`,
		identifyingCharacters: 'kazeso',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/99_hitomo.jpg`,
		identifyingCharacters: 'hitomo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		identifyingCharacters: 'momo',
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/00_momo.jpg`,
		verseFirstPart: '',
		verseSecondPart: '',
	},
];
