import type { KarutaCard } from '../interfaces/karuta-card.interface';

const KARUTA_CARD_ASSET_PATH = '/assets/images/karuta-cards';

export const KARUTA_CARDS: KarutaCard[] = [
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/01_akino.jpg`,
		identifyingCharacters: 'akino',
		verseFirstPart: 'aki no ta no<br />kariho no io no<br />toma wo arami',
		verseSecondPart: 'wa ga koromode wa<br />tsuyu ni nuretsutsu',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/02_harusu.jpg`,
		identifyingCharacters: 'harusu',
		verseFirstPart: 'haru sugite<br />natsu kinikerashi<br />shirotae no',
		verseSecondPart: 'koromo hosu chō<br />Ama no Kaguyama',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/03_ashi.jpg`,
		identifyingCharacters: 'ashi',
		verseFirstPart: 'ashibiki no<br />yamadori no ō no<br />shidari no ō no',
		verseSecondPart: 'naga nagashi yo wo<br />hitori kamo nen',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/04_tago.jpg`,
		identifyingCharacters: 'tago',
		verseFirstPart: 'tago no ura ni<br />uchi idete mireba<br />shirotae no',
		verseSecondPart: 'fuji no takane ni<br />yuki wa furitsutsu',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/05_oku.jpg`,
		identifyingCharacters: 'oku',
		verseFirstPart: 'okuyama ni<br />momiji fumiwake<br />naku shika no',
		verseSecondPart: 'koe kiku toki zo<br />aki wa kanashiki',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/06_kasa.jpg`,
		identifyingCharacters: 'kasa',
		verseFirstPart: 'kasasagi no<br />wataseru hashi ni<br />oku shimo no',
		verseSecondPart: 'shiroki wo mireba<br />yo zo fukenikeru',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/07_amano.jpg`,
		identifyingCharacters: 'amano',
		verseFirstPart: 'ama no hara<br />furisake mireba<br />kasuga naru',
		verseSecondPart: 'Mikasa no yama ni<br />ideshi tsuki kamo',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/08_wagai.jpg`,
		identifyingCharacters: 'wagai',
		verseFirstPart: 'wa ga io wa<br />miyako no tatsumi<br />shika zo sumu',
		verseSecondPart: 'yo wo ujiyama to<br />hito wa iu nari',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/09_hanano.jpg`,
		identifyingCharacters: 'hanano',
		verseFirstPart: 'hana no iro wa<br />utsurinikeri na<br />itazura ni',
		verseSecondPart: 'wa ga mi yo ni furu<br />nagame seshi ma ni',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/10_kore.jpg`,
		identifyingCharacters: 'kore',
		verseFirstPart: 'kore ya kono<br />yuku mo kaeru mo<br />wakarete wa',
		verseSecondPart: 'shiru mo shiranu mo<br />Ōsaka no seki',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/11_watanoharaya.jpg`,
		identifyingCharacters: 'watanoharaya',
		verseFirstPart: 'wata no hara<br />yasoshima kakete<br />kogi idenu to',
		verseSecondPart: 'hito ni wa tsugeyo<br />ama no tsuribuné',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/12_amatsu.jpg`,
		identifyingCharacters: 'amatsu',
		verseFirstPart: 'ama tsu kaze<br />kumo no kayoiji<br />fuki toji yo',
		verseSecondPart: 'otome no sugata<br />shibashi todomen',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/13_tsuku.jpg`,
		identifyingCharacters: 'tsuku',
		verseFirstPart: 'Tsukuba-ne no<br />mine yori otsuru<br />minano-gawa',
		verseSecondPart: 'koi zo tsumorite<br />fuchi to narinuru',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/14_michi.jpg`,
		identifyingCharacters: 'michi',
		verseFirstPart: 'michinoku no<br />Shinobu mojizuri<br />tare yue ni',
		verseSecondPart: 'midare some ni<br />ware naranaku ni',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/15_kimigatameha.jpg`,
		identifyingCharacters: 'kimigatameha',
		verseFirstPart: 'kimi ga tame<br />haru no no ni idete<br />wakana tsumu',
		verseSecondPart: 'waga koromode ni<br />yuki wa furitsutsu',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/16_tachi.jpg`,
		identifyingCharacters: 'tachi',
		verseFirstPart: 'tachiwakare<br />inaba no yama no<br />mine ni ouru',
		verseSecondPart: 'matsu to shi kikaba<br />ima kaeri-kon',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/17_chiha.jpg`,
		identifyingCharacters: 'chiha',
		verseFirstPart: 'chihayaburu<br />kami-yo mo kikazu<br />tatsuta-gawa',
		verseSecondPart: 'kara-kurenai ni<br />mizu kuguru to wa',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/18_su.jpg`,
		identifyingCharacters: 'su',
		verseFirstPart: 'sumi no e no<br />kishi ni yoru nami<br />yoru sae ya',
		verseSecondPart: 'yume no kayoi ji<br />hito me yoku ran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/19_naniwaga.jpg`,
		identifyingCharacters: 'naniwaga',
		verseFirstPart: 'Naniwa gata<br />mijikaki ashi no<br />fushi no ma mo',
		verseSecondPart: 'awade kono yo wo<br />sugushite yo to ya',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/20_wabi.jpg`,
		identifyingCharacters: 'wabi',
		verseFirstPart: 'wabi nureba<br />ima hata onaji<br />naniwa naru',
		verseSecondPart: 'mi wo tsukushitemo<br />awan to zo omou',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/21_imako.jpg`,
		identifyingCharacters: 'imako',
		verseFirstPart: 'ima kon to<br />iishi bakari ni<br />nagatsuki no',
		verseSecondPart: 'ariake no tsuki wo<br />machi idetsuru ka na',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/22_fu.jpg`,
		identifyingCharacters: 'fu',
		verseFirstPart: 'fuku kara ni<br />aki no kusaki no<br />shiorureba',
		verseSecondPart: 'mube yamakaze wo<br />arashi to iuran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/23_tsuki.jpg`,
		identifyingCharacters: 'tsuki',
		verseFirstPart: 'tsuki mireba<br />chiji ni mono koso<br />kanashi kere',
		verseSecondPart: 'waga mi hitotsu no<br />aki ni wa aranedo',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/24_kono.jpg`,
		identifyingCharacters: 'kono',
		verseFirstPart: 'kono tabi wa nusa mo<br />toriaezu tamuke yama',
		verseSecondPart: 'momiji no nishiki<br />kami no mani mani',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/25_nanishi.jpg`,
		identifyingCharacters: 'nanishi',
		verseFirstPart: 'na ni shi owaba<br />osakayama no<br />sanekazura',
		verseSecondPart: 'hito ni shirarede<br />kuru yoshi mo gana',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/26_ogu.jpg`,
		identifyingCharacters: 'ogu',
		verseFirstPart: 'ogurayama<br />mine no mojijiba<br />kokoro araba',
		verseSecondPart: 'ima hitotabi no<br />miyuki matanan',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/27_mikano.jpg`,
		identifyingCharacters: 'mikano',
		verseFirstPart: 'mika no hara<br />wakite nagaruru<br />izumi-gawa',
		verseSecondPart: 'itsu mi kitote ka<br />koishi karuran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/28_yamaza.jpg`,
		identifyingCharacters: 'yamaza',
		verseFirstPart: 'yamazato wa<br />fuyu zo sabishisa<br />masarikeru',
		verseSecondPart: 'hitome mo kusa mo<br />karenu omoeba',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/29_kokoroa.jpg`,
		identifyingCharacters: 'kokoroa',
		verseFirstPart: 'kokoroate ni<br />orabaya oran<br />hatsushimo no',
		verseSecondPart: 'oki madowaseru<br />shiragiku no hana',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/30_aria.jpg`,
		identifyingCharacters: 'aria',
		verseFirstPart: 'ariake no<br />tsurenaku mieshi<br />wakare yori',
		verseSecondPart: 'akatsuki bakari<br />uki mono wa nashi',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/31_asaborakea.jpg`,
		identifyingCharacters: 'asaborakea',
		verseFirstPart: 'asaborake<br />ariake no tsuki to<br />miru made ni',
		verseSecondPart: 'yoshino no sato ni<br />fureru shirayuki',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/32_yamaga.jpg`,
		identifyingCharacters: 'yamaga',
		verseFirstPart: 'yamagawa ni<br />kaze no kaketaru<br />shigarami wa',
		verseSecondPart: 'nagaremo aenu<br />momiji narikeri',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/33_hisa.jpg`,
		identifyingCharacters: 'hisa',
		verseFirstPart: 'hisakata no<br />hikari nodokeki<br />haru no hi ni',
		verseSecondPart: 'shizu-gokoro naku<br />hana no chiruran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/34_tare.jpg`,
		identifyingCharacters: 'tare',
		verseFirstPart: 'tare wo kamo<br />shiru hito ni sen<br />takasago no',
		verseSecondPart: 'matsu mo mukashi no<br />tomo nara naku ni',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/35_hitowa.jpg`,
		identifyingCharacters: 'hitowa',
		verseFirstPart: 'hito wa isa<br />kokoro mo shirazu<br />furusato wa',
		verseSecondPart: 'hana zo mukashi no<br />ka ni nioikeru',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/36_natsu.jpg`,
		identifyingCharacters: 'natsu',
		verseFirstPart: 'natsu no yo wa<br />mada yoi nagara<br />akenuru wo',
		verseSecondPart: 'kumo no izuko ni<br />tsuki yadoru ran',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/37_shira.jpg`,
		identifyingCharacters: 'shira',
		verseFirstPart: 'shiratsuyu wo<br />kaze no fukishiku<br />aki no no wa',
		verseSecondPart: 'tsuranuki tomenu<br />tama zo chiri keru',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/38_wasura.jpg`,
		identifyingCharacters: 'wasura',
		verseFirstPart: 'wasuraruru<br />mi wo ba omowazu<br />chikaite shi',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/39_asaji.jpg`,
		identifyingCharacters: 'asaji',
		verseFirstPart: 'asajiu no<br />ono no shinohara<br />shinoburedo',
		verseSecondPart: 'amarite nado ka<br />hito no koishiki',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/40_shino.jpg`,
		identifyingCharacters: 'shino',
		verseFirstPart: 'shinoburedo<br />iro ni idenikeri<br />wa ga koi wa',
		verseSecondPart: 'mono ya omou to<br />hito no tou made',
	},
	// https://onethousandsummers.blogspot.com/p/chouyaku-hyakuninisshu.html
	// https://100poets.com/index/
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/41_koi.jpg`,
		identifyingCharacters: 'koi',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/42_chigiriki.jpg`,
		identifyingCharacters: 'chigiriki',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/43_ai.jpg`,
		identifyingCharacters: 'ai',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/44_ooko.jpg`,
		identifyingCharacters: 'ooko',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/45_aware.jpg`,
		identifyingCharacters: 'aware',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/46_yura.jpg`,
		identifyingCharacters: 'yura',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/47_yae.jpg`,
		identifyingCharacters: 'yae',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/48_kazeo.jpg`,
		identifyingCharacters: 'kazeo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/49_mikaki.jpg`,
		identifyingCharacters: 'mikaki',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/50_kimigatameo.jpg`,
		identifyingCharacters: 'kimigatameo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/51_kaku.jpg`,
		identifyingCharacters: 'kaku',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/52_ake.jpg`,
		identifyingCharacters: 'ake',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/53_nageki.jpg`,
		identifyingCharacters: 'nageki',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/54_wasure.jpg`,
		identifyingCharacters: 'wasure',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/55_taki.jpg`,
		identifyingCharacters: 'taki',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/56_araza.jpg`,
		identifyingCharacters: 'araza',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/57_me.jpg`,
		identifyingCharacters: 'me',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/58_arima.jpg`,
		identifyingCharacters: 'arima',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/59_yasu.jpg`,
		identifyingCharacters: 'yasu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/60_ooe.jpg`,
		identifyingCharacters: 'ooe',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/61_ini.jpg`,
		identifyingCharacters: 'ini',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/62_yoo.jpg`,
		identifyingCharacters: 'yoo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/63_imawa.jpg`,
		identifyingCharacters: 'imawa',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/64_asaborakeu.jpg`,
		identifyingCharacters: 'asaborakeu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/65_ura.jpg`,
		identifyingCharacters: 'ura',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/66_moro.jpg`,
		identifyingCharacters: 'moro',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/67_haruno.jpg`,
		identifyingCharacters: 'haruno',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/68_kokoroni.jpg`,
		identifyingCharacters: 'kokoroni',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/69_arashi.jpg`,
		identifyingCharacters: 'arashi',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/70_sa.jpg`,
		identifyingCharacters: 'sa',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/71_yuu.jpg`,
		identifyingCharacters: 'yuu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/72_oto.jpg`,
		identifyingCharacters: 'oto',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/73_taka.jpg`,
		identifyingCharacters: 'taka',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/74_uka.jpg`,
		identifyingCharacters: 'uka',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/75_chigirio.jpg`,
		identifyingCharacters: 'chigirio',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/76_watanoharako.jpg`,
		identifyingCharacters: 'watanoharako',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/77_se.jpg`,
		identifyingCharacters: 'se',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/78_awaji.jpg`,
		identifyingCharacters: 'awaji',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/79_akika.jpg`,
		identifyingCharacters: 'akika',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/80_nagaka.jpg`,
		identifyingCharacters: 'nagaka',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/81_ho.jpg`,
		identifyingCharacters: 'ho',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/82_omo.jpg`,
		identifyingCharacters: 'omo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/83_yononakayo.jpg`,
		identifyingCharacters: 'yononakayo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/84_nagara.jpg`,
		identifyingCharacters: 'nagara',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/85_yomo.jpg`,
		identifyingCharacters: 'yomo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/86_nageke.jpg`,
		identifyingCharacters: 'nageke',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/87_mu.jpg`,
		identifyingCharacters: 'mu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/88_naniwae.jpg`,
		identifyingCharacters: 'naniwae',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/89_tama.jpg`,
		identifyingCharacters: 'tama',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/90_mise.jpg`,
		identifyingCharacters: 'mise',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/91_kiri.jpg`,
		identifyingCharacters: 'kiri',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/92_wagaso.jpg`,
		identifyingCharacters: 'wagaso',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/93_yononakawa.jpg`,
		identifyingCharacters: 'yononakawa',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/94_miyo.jpg`,
		identifyingCharacters: 'miyo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/95_ooke.jpg`,
		identifyingCharacters: 'ooke',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/96_hanasa.jpg`,
		identifyingCharacters: 'hanasa',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/97_konu.jpg`,
		identifyingCharacters: 'konu',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/98_kazeso.jpg`,
		identifyingCharacters: 'kazeso',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/99_hitomo.jpg`,
		identifyingCharacters: 'hitomo',
		verseFirstPart: '',
		verseSecondPart: '',
	},
	{
		identifyingCharacters: 'momo',
		imageSrc: `${KARUTA_CARD_ASSET_PATH}/00_momo.jpg`,
		verseFirstPart: '',
		verseSecondPart: '',
	},
];
